### PR TITLE
fix: ensure getMetrics and getTimings are always available

### LINKED ISSUE #191: `req.getMetrics` and `req.getTimings` undefined in error cases
In certain scenarios like `ECONNRESET`, these methods are not yet set up and would throw:

```
    Error: socket hang up (code="ECONNRESET")
        at createHangUpError (_http_client.js:254:15)
        at Socket.socketOnEnd (_http_client.js:346:23)
        at emitNone (events.js:91:20)
        at Socket.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)
Uncaught TypeError: req.getMetrics is not a function
```

We should either create noops for these, and or do best effort to capture what metrics/timings we can.

### PR DESCRIPTION
**Pull request by DonutEspresso**
Fixes #191

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Seems node11's `process.versions.openssl` is returning an empty space and new line char `\n`, which is throwing errors when we try to set the user-agent header. Going to ignore that error and address separately.

File: test/index.js [hunk 1]
```diff
@@ -554,6 +558,31 @@ describe('restify-client tests', function () {
...
+        it('should return best effort metrics and timings in error scenarios',
+        function (done) {
+            METRICS_CLIENT_HOST.get('/econnreset', function (err, req, res) {
+                assert.ok(err);
+                assert.strictEqual(err.code, 'ECONNRESET');
+            });
+
+            METRICS_CLIENT_HOST.once('metrics', function (metrics) {
+                assert.isObject(metrics);
+                assert.strictEqual(metrics.statusCode.toString(), 'NaN');
```
Comment (DonutEspresso) [inline test/index.js]: Is `NaN` the best value?
