### PR TITLE
Breaking: throw on missing protocol in url options

### LINKED ISSUE #141: passing a bare hostname for "url" causes client to connect to "localhost"
If consumers of the client pass a bare hostname for the `url` option to the client factory methods, the resulting client will unfortunately make requests to _localhost_.

This appears to be a result of lax checking of the output from the borderline byzantine `url.parse()` provided as part of the Node standard library.  For example, if the value `server.example.com` is provided as `url`, the following is the parsed result:

```json
{
    "protocol": null,
    "slashes": null,
    "auth": null,
    "host": null,
    "port": null,
    "hostname": null,
    "hash": null,
    "search": null,
    "query": null,
    "pathname": "server.example.com",
    "path": "server.example.com",
    "href": "server.example.com"
}
```

This is so wrong as to be actively dangerous.  One need not think for a long time to imagine security issues that could result from convincing a poorly constructed application to make requests against itself.

I think we should probably check the value of `protocol` to make sure it is either `"http:"` or `"https:"`.  If not, we should likely throw.

### PR DESCRIPTION
**Pull request by DonutEspresso**
Fixes #141 

The behavior of `url.parse` is kind of mind blowing, too.

### CODE REVIEW

File: lib/HttpClient.js [hunk 1]
```diff
@@ -442,6 +442,17 @@ function HttpClient(options) {
...
+        var parsedUrl = url.parse(options.url);
+        assert.ok(
+            parsedUrl.protocol === 'http:' || parsedUrl.protocol === 'https:',
+            'must specify http/https protocol!'
+        );
+        this.url = options.url;
+    } else {
+        this.url = {};
+    }
     this.url = options.url ? url.parse(options.url) : {};
```
Comment (retrohacker) [inline lib/HttpClient.js]: How does `this.url` not get blown away by this line?

**Comment by DonutEspresso** [comment]
Nice find @retrohacker! Fixed and rebased against master.

File: test/HttpClient.test.js [hunk 2]
```diff
@@ -26,12 +26,14 @@ describe('HttpClient', function () {
             CLIENT = clients.createHttpClient({
                 url: 'http://www.restify.com'
             });
-            assert.strictEqual(CLIENT.url.protocol, 'http:');
+        });
+        assert.strictEqual(CLIENT.url.protocol, 'http:');
 
+        assert.doesNotThrow(function () {
```
Comment (retrohacker) [inline test/HttpClient.test.js]: What is the behavior of `doesNotThrow` when you don't provide any other arguments? Does it just re-throw this error? Do we need an assert here? If it throws, wont the test fail?

http://chaijs.com/api/assert/#method_doesnotthrow

Comment (DonutEspresso) [reply test/HttpClient.test.js]: Correct, it just rethrows. In this case you're right, we probably don't need it, but I usually leave it in just to be explicit about what I'm testing (and in some scenarios where behavior may not be obvious because you're depending on default behavior). Don't feel super strongly though, if you'd prefer to remove it.
